INSERT INTO EMPLEADOS (ID_EMPLEADO , NOMBRE, PUESTO) VALUES (1,'MAURICIO', 'GERENTE');
INSERT INTO EMPLEADOS (ID_EMPLEADO , NOMBRE, PUESTO) VALUES (2,'M', 'SUB-GERENTE');
INSERT INTO EMPLEADOS (ID_EMPLEADO , NOMBRE, PUESTO) VALUES (3,'G', 'SUPERVISOR');


INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODUCTO, PRECIO) VALUES (01, 'VAPORIZADOR', 10000);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODUCTO, PRECIO) VALUES (02, 'PLAY5', 10000);
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODUCTO, PRECIO) VALUES (03, 'PC GAMER', 10000);

INSERT INTO ORDENES (ID_ORDEN , ID_EMPLEADO, ID_PRODUCTO, FECHA_ORDEN, CANTIDAD ) VALUES (1, 1,01, '2025-06-11', 11);
INSERT INTO ORDENES (ID_ORDEN , ID_EMPLEADO, ID_PRODUCTO,FECHA_ORDEN, CANTIDAD ) VALUES (2, 2,02, '2025-06-11', 5);
INSERT INTO ORDENES (ID_ORDEN , ID_EMPLEADO, ID_PRODUCTO,FECHA_ORDEN, CANTIDAD ) VALUES (3, 3,03, '2025-06-11', 3);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT PRIMARY KEY,
NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
PRECIO DECIMAL(10, 2) NOT NULL
);

CREATE TABLE ORDENES (
ID_ORDEN INT PRIMARY KEY,
ID_EMPLEADO INT,
ID_PRODUCTO INT,
FECHA_ORDEN DATE NOT NULL,
CANTIDAD INT NOT NULL,
FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);



INSERT INTO ORDENES (ID_PRODUCTO) VALUES (1), (2), (3);


DROP TABLE PRODUCTOS;

DROP TABLE PRODUCTOS;
SELECT * FROM ORDENES;


